/**
 * Deal Brief Agent.
 *
 * Generates an executive-ready M&A briefing for a target from its
 * fundamentals, recent signals, and fit score. Uses OpenAI when
 * OPENAI_API_KEY is configured; otherwise falls back to a deterministic
 * template so the feature works in every environment.
 *
 *   generateBrief(company, signals, score) -> { content, model }
 */
const { scoreCompany } = require('./scoring');

const MODEL = process.env.OPENAI_BRIEF_MODEL || 'gpt-4o-mini';

function eur(n) {
  if (n == null) return '—';
  const m = Number(n) / 1_000_000;
  if (m >= 1000) return `€${(m / 1000).toFixed(1)}B`;
  return `€${m.toFixed(m < 10 ? 1 : 0)}M`;
}

function factSheet(company) {
  return [
    `Name: ${company.name}`,
    `Sector: ${company.sector}`,
    `HQ: ${[company.hq_city, company.country].filter(Boolean).join(', ')}`,
    `Founded: ${company.founded_year || '—'}`,
    `Employees: ${company.employees ?? '—'}`,
    `Revenue: ${eur(company.revenue_eur)}`,
    company.arr_eur ? `ARR: ${eur(company.arr_eur)}` : null,
    `Growth: ${company.growth_rate != null ? company.growth_rate + '% YoY' : '—'}`,
    `Funding stage: ${company.funding_stage || '—'}`,
    `Ownership: ${company.ownership || '—'}`,
    `Indicative valuation: ${eur(company.valuation_eur)}`,
    `Description: ${company.description || '—'}`,
  ].filter(Boolean).join('\n');
}

function signalLines(signals) {
  if (!signals || signals.length === 0) return 'No active signals in the monitoring window.';
  return signals
    .slice(0, 8)
    .map((s) => {
      const when = new Date(s.signal_date || s.created_at).toISOString().slice(0, 10);
      const reg = s.regulator ? ` [${s.regulator}]` : '';
      return `- (${when}, ${s.severity}/${s.type}${reg}) ${s.title}${s.detail ? ' — ' + s.detail : ''}`;
    })
    .join('\n');
}

/** Deterministic template brief — no external calls. */
function templateBrief(company, signals, score) {
  const s = score || scoreCompany(company, { signals });
  const high = (signals || []).filter((x) => x.severity === 'high');
  const regulators = [...new Set((signals || []).map((x) => x.regulator).filter(Boolean))];

  const nextStep = s.total >= 75
    ? 'Move to outreach this week — fit is strong and signal momentum is live.'
    : s.total >= 55
      ? 'Add to the active screening list and set a 30-day signal trigger.'
      : 'Keep on the watchlist; revisit if a funding, leadership, or regulatory signal fires.';

  return `# Deal Brief — ${company.name}

**Fit score: ${s.total}/100 (${s.band})** · Top drivers: ${s.drivers.join(', ')}

## Snapshot
${company.name} is a ${company.sector} company headquartered in ${[company.hq_city, company.country].filter(Boolean).join(', ')}, founded ${company.founded_year || 'n/a'}. It runs at ${eur(company.revenue_eur)} revenue${company.arr_eur ? ` (${eur(company.arr_eur)} ARR)` : ''} with ${company.growth_rate != null ? company.growth_rate + '% YoY growth' : 'undisclosed growth'}, ${company.ownership || 'privately'}-held, indicative valuation ${eur(company.valuation_eur)}.

## Strategic rationale
- Sector heat scores ${company.sector_heat ?? 'n/a'}/100 — ${company.sector_heat >= 75 ? 'active consolidation, multiples expanding' : company.sector_heat >= 55 ? 'warming, selective deal flow' : 'stable, opportunistic only'}.
- Size sits ${Number(company.revenue_eur || 0) / 1e6 <= 150 && Number(company.revenue_eur || 0) / 1e6 >= 20 ? 'inside' : 'outside'} the mid-market sweet spot.
- Ownership (${company.ownership || 'private'}) is ${['pe-backed', 'vc-backed', 'family-owned'].includes((company.ownership || '').toLowerCase()) ? 'favourable — a transaction window is plausible' : 'less immediately transactable'}.

## Signal summary
${signalLines(signals)}
${high.length ? `\n**${high.length} high-severity signal${high.length === 1 ? '' : 's'} active.**` : ''}

## Regulatory & compliance
${regulators.length ? `Flags from: ${regulators.join(', ')}. Confirm filing status before an NDA.` : 'No active regulatory flags in the monitoring window. Standard EU/GDPR diligence applies.'}

## Recommended next step
${nextStep}

_Generated by Nexecutive — template engine (configure OPENAI_API_KEY for narrative briefs)._`;
}

/** OpenAI-backed narrative brief. Throws on any API/SDK error. */
async function openaiBrief(company, signals, score) {
  const OpenAI = require('openai');
  const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  const s = score || scoreCompany(company, { signals });

  const system =
    'You are a senior M&A analyst at a corporate development desk. Write concise, ' +
    'executive-ready deal briefs in Markdown. Be specific, quantitative, and neutral. ' +
    'Never invent figures beyond the data provided. Use these sections: Snapshot, ' +
    'Strategic rationale, Signal summary, Regulatory & compliance, Valuation context, ' +
    'Recommended next step.';

  const user =
    `Write a deal brief for this acquisition target.\n\n` +
    `FIT SCORE: ${s.total}/100 (${s.band}); top drivers: ${s.drivers.join(', ')}\n\n` +
    `FUNDAMENTALS:\n${factSheet(company)}\n\n` +
    `RECENT SIGNALS:\n${signalLines(signals)}\n`;

  const resp = await client.chat.completions.create({
    model: MODEL,
    messages: [
      { role: 'system', content: system },
      { role: 'user', content: user },
    ],
    temperature: 0.4,
    max_tokens: 900,
  });

  const content = resp.choices?.[0]?.message?.content?.trim();
  if (!content) throw new Error('Empty completion');
  return { content, model: MODEL };
}

async function generateBrief(company, signals = [], score = null) {
  if (process.env.OPENAI_API_KEY) {
    try {
      return await openaiBrief(company, signals, score);
    } catch (err) {
      console.error('[briefs] OpenAI failed, falling back to template:', err.message);
    }
  }
  return { content: templateBrief(company, signals, score), model: 'template' };
}

module.exports = { generateBrief, templateBrief };
